core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('discussion/start', views.DiscussionCreateView.as_view(), name="Discussion_start"),
    path('discussion/update/<uuid:pk>', views.DiscussionUpdateView.as_view(), name="Discussion_update"),
    path('discussions', views.DiscussionListView.as_view(), name="Discussions"),
    # path('discussion/detail/<uuid:pk>/Message', views.MessageCreateView.as_view(), name="Message_create"),
    path('discussion/<uuid:discussion_id>/messages', views.MessageListView.as_view(), name="Message_list"),
    path('discussion/<uuid:discussion_id>/toggle-like/', views.ToggleLikeView.as_view(), name='toggle_like'),
    path('modd', views.ModdView.as_view(), name="modd"),
]

mubahasa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("core.urls")),
    path("accounts/", include('accounts.urls')),
    path('', include('pwa.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    about = models.CharField(max_length=50, default='None')
    TYPE_OPTIONS = (
        ('Free','Free'),
        ('Premium','Premium'),
    )
    type = models.CharField(max_length=8,choices=TYPE_OPTIONS,default='Free')
    name = models.CharField(max_length=50)
    mobile_number = models.CharField(max_length=12)
    email = models.EmailField(max_length=254)

    def __str__(self):
        if self.user:
            return str(self.user.username)
        return str(self.name)
    def get_absolute_url(self):
        """
        Get the absolute URL for the patient's detail view.
        """
        return reverse("user_profile_detail", kwargs={"pk": self.id})

core/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Discussion(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    TYPE_OPTIONS = (
        ('Public','Public'),
        ('Private','Private'),
    )
    visibility = models.CharField(max_length=8,choices=TYPE_OPTIONS,default='Public')
    def __str__(self):
        return f"{self.title} | {self.creator.username}"

    def get_absolute_url(self):
        return reverse("Discussion_detail", kwargs={"pk": str(self.id)})

class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    body = models.TextField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.creator.username} | {self.created_at}"
 

    def get_absolute_url(self):
        return reverse("Message_detail", kwargs={"pk": str(self.id)})


class Like(models.Model):
    discussion = models.ForeignKey(Discussion, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)        

core/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Discussion,Message,Like
from django.views.generic import CreateView,UpdateView,DetailView,ListView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect

class ModdView(View):
    template_name = "modd.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class index(ListView):
    model = Discussion
    template_name = 'index.html'  
    context_object_name = 'Discussions'
    paginate_by = 10
    def get_queryset(self):
        discussions = Discussion.objects.filter(visibility='Public').annotate(num_likes=Count('like')).order_by('-num_likes')[:5]
        return discussions

class DiscussionCreateView(LoginRequiredMixin,SuccessMessageMixin,CreateView):
    model = Discussion
    template_name = "form.html"
    fields = ["title","description","visibility"]
    success_message = "Discussion Started!"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Start Discussion'
        return context
    def form_valid(self,form):
        form.instance.creator = self.request.user
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('Message_list', kwargs={'discussion_id': self.object.id})


    


class DiscussionUpdateView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = Discussion
    template_name = "form.html"
    fields = ["title","description","visibility"]
    success_message = "Discussion was successfully Updated!"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update Discussion'
        return context
    def form_valid(self,form):
        form.instance.creator = self.request.user
        return super().form_valid(form)  
    def get_success_url(self):
        return reverse('Message_list', kwargs={'discussion_id': self.object.id})

  
    
class DiscussionListView(ListView):
    model = Discussion
    context_object_name = "Discussions"
    paginate_by = 10
    template_name = "Discussion_list.html"
    def get_queryset(self):
        search_query = self.request.GET.get('q', '')
        private_arg = self.request.GET.get('private', '0')
        if self.request.user.is_authenticated:
            if self.request.user.is_superuser:
                queryset = Discussion.objects.all().order_by('-created_at')
            else:
                if private_arg == '1':
                    queryset = Discussion.objects.filter(creator=self.request.user, visibility='Private').order_by('-created_at')
                else:    
                    queryset = Discussion.objects.all().filter(visibility='Public').order_by('-created_at')
        else:
            queryset = Discussion.objects.all().filter(visibility='Public').order_by('-created_at')


        if search_query:
            queryset = queryset.filter(
                Q(title__icontains=search_query) |
                Q(description__icontains=search_query)
            )

        return queryset
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        top_discussions_by_user = Discussion.objects.filter(visibility='Public').values('creator__username').annotate(total_discussions=Count('id')).order_by('-total_discussions')[:10]
        context['top_discussions_by_user'] = top_discussions_by_user
        return context    

    
# class MessageCreateView(LoginRequiredMixin,SuccessMessageMixin, CreateView):
#     model = Message
#     template_name = "form.html"
#     fields = ["body"]
#     success_message = "Message Successfull!"
#     def form_valid(self,form):
#         discussion = get_object_or_404(Discussion, pk=self.kwargs['pk'])
#         form.instance.discussion = discussion
#         form.instance.creator = self.request.user
#         return super().form_valid(form)
#     def get_success_url(self):
#         return reverse('Message_list', kwargs={'discussion_id': self.kwargs['pk']})
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["title"] = "Message"
#         return context
    

class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = "Message_list.html"
    context_object_name = "Messages"
    paginate_by = 10

    def get_queryset(self):
        discussion_id = self.kwargs.get('discussion_id')
        if discussion_id:
            return Message.objects.filter(discussion__id=discussion_id).order_by('-created_at')
        else:
            return Message.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        discussion_id = self.kwargs.get('discussion_id')
        if discussion_id:
            discussion = get_object_or_404(Discussion, pk=discussion_id)
            context['discussion'] = discussion
            total_likes = Like.objects.filter(discussion=discussion).count()
            context['total_likes'] = total_likes
            user_has_liked = Like.objects.filter(discussion=discussion, user=self.request.user).exists()
            context['user_has_liked'] = user_has_liked
            participants = Message.objects.filter(discussion=discussion).values('creator__username').annotate(count=Count('creator')).order_by('-count')
            context['participants'] = participants

        return context

    def post(self, request, *args, **kwargs):
        discussion_id = self.kwargs.get('discussion_id')
        message_body = request.POST.get('message')

        try:
            if not discussion_id or not message_body:
                raise ValueError("Discussion ID or message body is missing.")

            discussion = get_object_or_404(Discussion, pk=discussion_id)
            creator = self.request.user
            message = Message.objects.create(
                creator=creator,
                body=message_body,
                discussion=discussion
            )
            messages.success(request, 'Message posted successfully.')
            return HttpResponseRedirect(reverse('Message_list', kwargs={'discussion_id': discussion_id}))
        except ValueError as e:
            messages.error(request, str(e))
            return HttpResponseRedirect(reverse('Message_list', kwargs={'discussion_id': discussion_id}))
        except Exception as e:
            messages.error(request, 'An error occurred while posting the message.')
            return HttpResponseRedirect(reverse('Message_list', kwargs={'discussion_id': discussion_id}))




class ToggleLikeView(View):
    def get(self, request, *args, **kwargs):
        discussion_id = kwargs.get('discussion_id')
        discussion = get_object_or_404(Discussion, pk=discussion_id)
        user = request.user
        existing_like = Like.objects.filter(discussion=discussion, user=user)
        if existing_like.exists():
            existing_like.delete()
        else:
            Like.objects.create(discussion=discussion, user=user)

        return redirect('Message_list', discussion_id=discussion_id)

core/templates/Discussion_list.html
{% extends 'base.html' %}
{% block og_title %}Discussions{% endblock og_title %}
{% block og_img_title %}Discussions{% endblock og_img_title %}
{% block og_desc %}Discussions on MUBAHASA{% endblock og_desc %}
{% block twitter_title %}Discussions{% endblock twitter_title %}
{% block twitter_img_title %}Discussions{% endblock twitter_img_title %}
{% block twitter_desc %}Discussions on MUBAHASA{% endblock twitter_desc %}
{% block title %}Discussions{% endblock title %}


{% block leftcontent %}

{% include 'search_box.html' %}
{% endblock leftcontent %}

{% block content %}

<a class="linkx" style="margin-left:1rem;" href="{% url 'Discussion_start' %}"><i class="fa-regular fa-comments"></i> Start Discussion</a>
{% if user.is_authenticated %}
{% if request.GET.private == '1' %}
<a class="linkx" style="margin-left:1rem;" href="{% url 'Discussions' %}"><i class="fa-solid fa-list"></i> Public Discussions</a>
{% else %}
<a class="linkx" style="margin-left:1rem;" href="{% url 'Discussions' %}?private=1"><i class="fa-solid fa-lock"></i> Private Discussions</a>
{% endif %}
{% endif %}
{% if Discussions %}
<h3 class="titlex">Discussions</h3>
<ul class="listx" >
{% for Discussion in Discussions  %}
    <li class="itemx"><a class="linky" href="{% url 'Message_list' Discussion.pk %}"><i class="fa-solid fa-arrow-turn-up fa-rotate-90"></i> {{ Discussion.title }} [ {% if request.user.is_superuser %}{{ Discussion.visibility }}{% endif %} {{ Discussion.created_at|timesince }} ago , by {{ Discussion.creator.username }}]</a></li>
{% endfor %}
{% else %}
<p>No Discussion Found! Start one! </p>
{% endif %}
{% endblock content %}


{% block rightcontent %}
{% if top_discussions_by_user %}
    <h3 class="titlex">Top 10 Users with the Most Discussions:</h3>
    <ul class="listx">
        {% for user_data in top_discussions_by_user %}
            <li class="itemx"><i class="fa-solid fa-user"></i> {{ user_data.creator__username }}: {{ user_data.total_discussions }} discussion{{ user_data.total_discussions|pluralize }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock rightcontent %}

core/templates/Message_list.html
{% extends 'base.html' %}
{% block og_title %}{{ discussion.title }}{% endblock og_title %}
{% block og_img_title %}{{ discussion.title }}{% endblock og_img_title %}
{% block og_desc %}{{ discussion.description }}{% endblock og_desc %}
{% block twitter_title %}{{ discussion.title }}{% endblock twitter_title %}
{% block twitter_img_title %}{{ discussion.title }}{% endblock twitter_img_title %}
{% block twitter_desc %}{{ discussion.description }}{% endblock twitter_desc %}
{% block title %}{{ discussion.title }}{% endblock title %}

{% block content %}
<div class="discussion-box">
<h2 class="titlex">{{ discussion.title }}</h2>
<h5 class="titlex">{{ discussion.visibility }} discussion Started at {{ discussion.created_at }} by <i class="fa-solid fa-user"></i> {{ discussion.creator.username }}</h5>
{% comment %} <a class="linkx" href="{% url 'Message_create' discussion.pk %}"><i class="fa-regular fa-message"></i> Post message [{{ Messages|length }}]</a> {% endcomment %}
<a href="{% url 'toggle_like' discussion.id %}" class="like-button {% if user_has_liked %}active{% endif %}">
    {% if user_has_liked %}
    <i class="fa-solid fa-heart fa-xl"></i>
    {% else %}
    <i class="fa-regular fa-heart"></i>
    {% endif %}[{{ total_likes }}]
</a>
<a class="like-button" href="https://wa.me/?text={{ request.build_absolute_uri }}" target="_blank">
    <i class="fab fa-whatsapp fa-xl"></i>
</a>
<a class="like-button" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank">
    <i class="fab fa-facebook fa-xl"></i>
</a>
<a class="like-button" href="https://twitter.com/intent/tweet?url={{ request.build_absolute_uri }}" target="_blank">
    <i class="fab fa-x-twitter" fa-xl></i>
</a>
<a class="like-button" href="https://www.linkedin.com/sharing/share-offsite/?url={{ request.build_absolute_uri }}" target="_blank">
    <i class="fab fa-linkedin fa-xl"></i>
</a>
<a class="like-button" href="mailto:?body={{ request.build_absolute_uri }}" target="_blank">
    <i class="fas fa-envelope fa-xl"></i>
</a>

<button class="like-button" style="border:none;" onclick="copyURL()"><i class="fas fa-copy fa-xl"></i></button>

<script>
  function copyURL() {
    var currentURL = window.location.href;
    var tempInput = document.createElement("input");
    tempInput.value = currentURL;
    document.body.appendChild(tempInput);
    tempInput.select();
    tempInput.setSelectionRange(0, 99999); 
    document.execCommand("copy");
    document.body.removeChild(tempInput);
    alert("Copied!")
  }
</script>

<p class="discussion-p"> {{ discussion.description|linebreaks }}</p>
</div>
<form method="post" action="{% url 'Message_list' discussion_id=discussion.id %}">
    {% csrf_token %}
    <textarea id="message" name="message" placeholder="Message" required></textarea>
    <br>
    <input type="submit" value="Post Message">
</form>

{% for message in Messages %}
<div class="message-box">
    <span class="message-meta"><span style="{% if message.creator == request.user %}color:Blue;{% endif %}"><i class="fa-solid fa-user"></i> {{ message.creator }}</span> | {{ message.created_at|timesince }} ago</span>
    <p class="message-body">{{ message.body }}</p>
</div>
{% endfor %}
{% endblock content %}

{% block rightcontent %}
{% if participants %}
<h3 class="titlex">Participants</h3>
<ul class="listx">
{% for participant in participants %}
    <li class="itemx"><i class="fa-solid fa-user"></i> {{ participant.creator__username }}</li>
{% endfor %}
</ul>
{% else %}
<p>No participant in Discussion except you. Be first to start!</p>
{% endif %}
{% endblock rightcontent %}

core/templates/base.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% progressive_web_app_meta %}
    <title>{% block title %} {% endblock title %} | Mubahasa</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-Avb2QiuDEEvB4bZJYdft2mNjVShBftLdPG8FJ0V7irTLQ8Uo0qcPxh4Plq7G5tGm0rU+1SPhVotteLpBERwTkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script src="{% static 'script.js' %}"></script>
    <link rel="shortcut icon" href="{% static 'favicon_io/favicon.ico' %}" type="image/x-icon">
    <meta content="MUBAHASA" name="title">
    <meta content="Mubahasa : Discussion App." name="description">
    <meta content="MODD" name="author">
    <!-- Open Graph / Facebook -->
    <meta content="{% block og_title %}{% endblock og_title %}| MUBAHASA" property="og:title">
    <meta content="{% block og_desc %}{% endblock og_desc %}Mubahasa : Discussion App" property="og:description">
    <meta content="{{ request.build_absolute_uri }}" property="og:url">
    <meta content="https://dynamic-og-image-generator.vercel.app//api/generate?title={% block og_img_title %}{% endblock og_img_title %}&author=MUBAHASA&avatar={{ request.scheme }}://{{ request.get_host }}{% static 'favicon_io/favicon.ico' %}&websiteUrl={{ request.build_absolute_uri }}&theme=dracula" property="og:image">

    <!-- Twitter -->
    <meta content="summary_large_image" property="twitter:card">
    <meta content="{{ request.build_absolute_uri }}" property="twitter:url">
    <meta content="{% block twitter_title %}{% endblock twitter_title %}| MUBAHASA" property="twitter:title">
    <meta content="{% block twitter_desc %}{% endblock twitter_desc %}Mubahasa : Discussion App" property="twitter:description">
    <meta content="https://dynamic-og-image-generator.vercel.app//api/generate?title={% block twitter_img_title %}{% endblock twitter_img_title %}&author=MUBAHASA&avatar={{ request.scheme }}://{{ request.get_host }}{% static 'favicon_io/favicon.ico' %}&websiteUrl={{ request.build_absolute_uri }}&theme=dracula" property="twitter:image">
</head>
<body>
    <header>
        <h1>MUBAHASA</h1>
        <h6 style="text-align:right;">Welcome! {% if user.is_authenticated %}{{ user.username }}{% else %}Guest.{% endif %}</h6>
    </header>

<nav>
    <ul>
        <li><a href="{% url 'index' %}"><i class="fa-solid fa-house fa-xl"></i>  </a></li>
        <li><a href="{% url 'Discussions' %}"><i class="fa-solid fa-comments fa-xl"></i> </a></li>
        {% if user.is_authenticated %}
        <li><a href="{% url 'profile' %}"><i class="fa-solid fa-id-card-clip fa-xl"></i> </a></li>
        <li><a href="{% url 'logout'%}?next={% url 'index' %}"><i class="fa-solid fa-right-from-bracket fa-xl"></i></a></li>
        {% else %}
        <li><a href="{% url 'login'%}"><i class="fa-solid fa-right-to-bracket fa-xl"></i> </a></li>
        <li><a href="{% url 'signup'%}?next={{request.path}}"><i class="fa-solid fa-user-plus fa-xl"></i></a></li>
        
        {% endif %}
    </ul>
    
</nav>

{% if messages %}
    <div class="notification-container" id="notifications">
        <ul class="notification">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
        <button class="close-btn"  onclick="closeMessage(this)"><i class="fa-solid fa-x"></i></button>
    </div>
{% endif %}

<div class="container">
    <div class="right-content">
        {% block rightcontent %}{% endblock %}
    </div>
    <div class="center-content">
        {% block content %}{% endblock %}
        {% block pagination %}
        {% if is_paginated %}
            <ul class="pagination">
    
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.private %}&private={{ request.GET.private }}{% endif %}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.private %}&private={{ request.GET.private }}{% endif %}">
                            {{ page_obj.previous_page_number }}
                        </a>
                    </li>
                {% endif %}
    
                <li class="page-item">
                    <a class="page-link active" href="#">
                        {{ page_obj.number }}
                    </a>
                </li>
    
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.private %}&private={{ request.GET.private }}{% endif %}">
                            {{ page_obj.next_page_number }}
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.private %}&private={{ request.GET.private }}{% endif %}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
    
            </ul>
        {% endif %}
    {% endblock %}
    </div>
    <div class="left-content">
        {% block leftcontent %}{% endblock %}
    </div>
</div>



    <footer>
        &#169; created by <a class="linky" href="{% url 'modd'%}">MODD</a>
    </footer>
</body>
</html>

core/templates/form.html
{% extends "base.html" %}
{% block og_title %}{{ title }}Discussions{% endblock og_title %}
{% block og_img_title %}{{ title }}Discussions{% endblock og_img_title %}
{% block og_desc %}{{ title }}Form{% endblock og_desc %}
{% block twitter_title %}{{ title }}Discussions{% endblock twitter_title %}
{% block twitter_img_title %}{{ title }}Discussions{% endblock twitter_img_title %}
{% block twitter_desc %}{{ title }}Form{% endblock twitter_desc %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<div class="form-container">
        <h1 class="titlex">{{ title }}</h1> 
        <form method="post">
            {% csrf_token %}
            {{ form }}<br>
            <input type="submit" value="{{ title }}"> 
        </form>
    </div>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% block og_title %}Index{% endblock og_title %}
{% block og_img_title %}Index{% endblock og_img_title %}
{% block og_desc %}Welcome! to Mubahasa{% endblock og_desc %}
{% block twitter_title %}Index{% endblock twitter_title %}
{% block twitter_img_title %}Index{% endblock twitter_img_title %}
{% block twitter_desc %}Welcome to Mubahasa{% endblock twitter_desc %}
{% block title %}Discussions{% endblock title %}

{% block content %}
 {% if user.is_superuser %}
                  <a class="linkx" href="{% url 'admin:index' %}"><span>Admin Panel</span></a>
                  <a class="linkx" href="{% url 'profile_list' %}"><span>Profile List</span></a> 
                    {% endif %}
<a class="linkx" style="margin-left:1rem;" href="{% url 'Discussion_start' %}"><i class="fa-regular fa-comments"></i> Start Discussion</a>

{% if Discussions %}
<h3 class="titlex"> <i class="fa-solid fa-arrow-trend-up"></i> Most Liked Discussions</h3>
<ul class="listx" >
{% for Discussion in Discussions  %}
    <li class="itemx"><a class="linky" href="{% url 'Message_list' Discussion.pk %}"><i class="fa-solid fa-arrow-turn-up fa-rotate-90"></i> {{ Discussion.title }} [{{ Discussion.created_at|timesince }} ago , by {{ Discussion.creator.username }}]</a></li>
{% endfor %}
{% else %}
<p>No Discussion Found! Start one! </p>
{% endif %}
{% endblock content %}

core/templates/modd.html
{% extends 'base.html' %}

{% block title %}MODD{% endblock title %}

{% block content %}
    <style>
        .social-card {
            background-color: #333;
            color: #fff;
            padding: 20px;
            border-radius: 10px;
            text-align: center;
          }
      
          .social-link {
            display: inline-block;
            margin: 0 10px;
            color: #fff;
            text-decoration: none;
            font-size: 20px;
            border: 2px solid #fff;
            padding: 5px 5px;
            border-radius:3px;
          }
      
          .social-link i {
            margin-right: 5px;
          }
    </style>
    <div class="social-card">
        <h1>MODD</h1>
        <p>Connect with me:</p>
        <a href="https://darksied.pages.dev" class="social-link" target="_blank"><i class="fa-solid fa-skull"></i> Everywhere</a>
      </div>




{% endblock content %}

core/templates/search_box.html
<form action="{% url 'Discussions' %}" method="get">
    <input type="text" name="q" placeholder="Search" id="q">
    <button class="form-button"type="submit"><i class="fa-solid fa-magnifying-glass"></i> Explore</button> 
</form>